import { Inter } from "next/font/google";
import NavBanner from "./NavBanner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const currentDate = new Date();

export const metadata = {
    title: "TuTuft, LLC.",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    let year = currentDate.getFullYear();

    return (
        <html lang="en">
            <body className={`h-full ${inter.className}`}>
                <div className="w-full">
                    <NavBanner />
                </div>
                This is the main container
                {children}
                
                <footer className="mt-[.5%] text-center border border-red-800 text-[150%]">
                    copyright {year}
                </footer>
            </body>
        </html>
    );
}
