// Importing necessary modules and components
import { Inter } from "next/font/google"; // Google font
import NavBanner from "./NavBanner"; // Navigation banner component
import "./globals.css"; // Global styles
import "leaflet/dist/leaflet.css"; // Leaflet for maps styling
import { SpeedInsights } from "@vercel/speed-insights/next"; // Speed insights for performance
import { CartProvider } from "./cart/CartContext"; // Context provider for cart functionality

const inter = Inter({ subsets: ["latin"] }); // Load Inter font with Latin subset
const currentDate = new Date(); // Current date instance

// Metadata for SEO purposes
export const metadata = {
    title: "TuTuft, LLC.", // Title of the site
    description: "Generated by create next app" // Description
};

// Root layout component that wraps around children components
const RootLayout = ({ children }) => {
    let year = currentDate.getFullYear(); //Current year for the footer

    // Component rendering
    return (
        <CartProvider>
            <html lang="en">
                <body className={` ${inter.className} `}>
                    <div className="flex flex-col items-center text-center bg-gradient-to-b to-green-600 from-slate-100">
                        <header className="w-full bg-white z-50">
                            <NavBanner />
                        </header>
                        This is the main container
                        <div className="flex flex-col h-[95%] w-[95%] border border-yellow-200 text-center items-center">
                            {children}
                            <SpeedInsights />
                        </div>
                        <footer className="flex flex-col mt-[.5%] text-center justify-center border border-red-800 desktop:text-[150%] laptop:w-[55%]">
                            copyright &copy; {year}
                        </footer>
                    </div>
                </body>
            </html>
        </CartProvider>
    );
};

export default RootLayout;
