// Importing necessary modules and components
import { Inter } from "next/font/google"; // Google font
import NavBanner from "./NavBanner"; // Navigation banner component
import "./globals.css"; // Global styles
import "leaflet/dist/leaflet.css"; // Leaflet for maps styling
import { SpeedInsights } from "@vercel/speed-insights/next"; // Speed insights for performance
import { CartProvider } from "./cart/CartContext"; // Context provider for cart functionality

const inter = Inter({ subsets: ["latin"] }); // Load Inter font with Latin subset
const currentDate = new Date(); // Current date instance

// Metadata for SEO purposes
export const metadata = {
    title: "TuTuft, LLC.", // Title of the site
    description: "Generated by create next app" // Description
};

// Root layout component that wraps around children components
const RootLayout = ({ children }) => {
    let year = currentDate.getFullYear(); //Current year for the footer

    // Component rendering
    return (
        <CartProvider>
            <html lang="en">
                <body
                    className={` ${inter.className} bg-gradient-to-b to-emerald-950 from-emerald-100`}
                >
                    <div className="flex flex-col items-center text-center">
                        <header className="w-[95%] z-50 h-[2.5%] ">
                            <NavBanner />
                        </header>
                        {/* This is the main container */}
                        <div className="flex flex-col h-[92.5%] my-[2%] w-[95%] text-center items-center">
                            {children}
                            <SpeedInsights />
                        </div>
                        <footer className="flex flex-col h-[5%] my-[5%] text-center justify-center text-sm desktop:text-[100%] laptop:w-[55%]">
                            <p className="my-1">
                                Brought to you by TuTuft, LLC.
                            </p>
                            <p className="my-1">Design by TD Solutions,LLC.</p>
                            copyright &copy; {year}
                        </footer>
                    </div>
                </body>
            </html>
        </CartProvider>
    );
};

export default RootLayout;
